name: Build & Release (.NET 8)

env:
    PROJECT_NAME: CsSpawnsPlugin
    CONFIGURATION: Release
    DOTNET_VERSION: 8.0.x
    PROJECT_PATH: $PROJECT_NAME/$PROJECT_NAME.csproj

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore $PROJECT_PATH

      - name: Build (Release)
        run: |
          dotnet build $PROJECT_PATH \
            --configuration Release \
            --no-restore

      - name: Publish DLL
        run: |
          dotnet publish $PROJECT_PATH \
            --configuration Release \
            --framework net8.0 \
            --no-restore \
            --output ./publish

      - name: Zip release artifact
        run: |
          cd publish
          zip -r publish/$PROJECT_NAME-${{ github.ref_name }}.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: publish/$PROJECT_NAME-${{ github.ref_name }}.zip